spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/darvera/services-yamls
          #searchPaths: '/{application}/{profile}'
          cloneOnStart: true
  #profiles:
  #  active: dev

server:
  port: 8888